name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'lably-backend/**'
  pull_request:
    paths: 
      - 'lably-backend/**'
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/lably
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      GMAIL_USER: ${{secrets.GMAIL_USER}}
      GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}
      NODE_ENV: test
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lably
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: lably-backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('lably-backend/package-lock.json') }}

      - name: Install dependencies
        run: npm install
        working-directory: lably-backend

      - name: Install psql client
        run: sudo apt-get install -y postgresql-client

      - name: Setup database
        run: psql postgresql://postgres:postgres@localhost:5432/lably -f database.sql
        working-directory: lably-backend

      - name: Run tests
        run: npm test
        working-directory: lably-backend

      - name: Deploy to Render
        if: success()
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"
